# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/AddFortModifierResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Responses/AddFortModifierResponse.proto',
  package='POGOProtos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\n=POGOProtos/Networking/Responses/AddFortModifierResponse.proto\x12\x1fPOGOProtos.Networking.Responses\"\x19\n\x17\x41\x64\x64\x46ortModifierResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDFORTMODIFIERRESPONSE = _descriptor.Descriptor(
  name='AddFortModifierResponse',
  full_name='POGOProtos.Networking.Responses.AddFortModifierResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['AddFortModifierResponse'] = _ADDFORTMODIFIERRESPONSE

AddFortModifierResponse = _reflection.GeneratedProtocolMessageType('AddFortModifierResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDFORTMODIFIERRESPONSE,
  __module__ = 'POGOProtos.Networking.Responses.AddFortModifierResponse_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.AddFortModifierResponse)
  ))
_sym_db.RegisterMessage(AddFortModifierResponse)


# @@protoc_insertion_point(module_scope)
