# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Envelopes/Unknown6Response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Envelopes/Unknown6Response.proto',
  package='POGOProtos.Networking.Envelopes',
  syntax='proto3',
  serialized_pb=_b('\n6POGOProtos/Networking/Envelopes/Unknown6Response.proto\x12\x1fPOGOProtos.Networking.Envelopes\"\x90\x01\n\x10Unknown6Response\x12\x10\n\x08unknown1\x18\x01 \x01(\x05\x12L\n\x08unknown2\x18\x02 \x01(\x0b\x32:.POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2\x1a\x1c\n\x08Unknown2\x12\x10\n\x08unknown1\x18\x01 \x01(\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UNKNOWN6RESPONSE_UNKNOWN2 = _descriptor.Descriptor(
  name='Unknown2',
  full_name='POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.unknown1', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=236,
)

_UNKNOWN6RESPONSE = _descriptor.Descriptor(
  name='Unknown6Response',
  full_name='POGOProtos.Networking.Envelopes.Unknown6Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='POGOProtos.Networking.Envelopes.Unknown6Response.unknown1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown2', full_name='POGOProtos.Networking.Envelopes.Unknown6Response.unknown2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_UNKNOWN6RESPONSE_UNKNOWN2, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=236,
)

_UNKNOWN6RESPONSE_UNKNOWN2.containing_type = _UNKNOWN6RESPONSE
_UNKNOWN6RESPONSE.fields_by_name['unknown2'].message_type = _UNKNOWN6RESPONSE_UNKNOWN2
DESCRIPTOR.message_types_by_name['Unknown6Response'] = _UNKNOWN6RESPONSE

Unknown6Response = _reflection.GeneratedProtocolMessageType('Unknown6Response', (_message.Message,), dict(

  Unknown2 = _reflection.GeneratedProtocolMessageType('Unknown2', (_message.Message,), dict(
    DESCRIPTOR = _UNKNOWN6RESPONSE_UNKNOWN2,
    __module__ = 'POGOProtos.Networking.Envelopes.Unknown6Response_pb2'
    # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2)
    ))
  ,
  DESCRIPTOR = _UNKNOWN6RESPONSE,
  __module__ = 'POGOProtos.Networking.Envelopes.Unknown6Response_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Envelopes.Unknown6Response)
  ))
_sym_db.RegisterMessage(Unknown6Response)
_sym_db.RegisterMessage(Unknown6Response.Unknown2)


# @@protoc_insertion_point(module_scope)
